sudo: required
services:
  - docker

language: python

stages:
  - test
  - delivery
  - submit

jobs:
  include:
    - stage: test
      python: 2.7
      env: TOXENV=py27-codeclimate
      install:
          - pip install tox
      script:
          - tox

    - stage: test
      python: 3.6
      env: TOXENV=py36-codeclimate
      before_script:
          - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          - chmod +x ./cc-test-reporter
          - ./cc-test-reporter before-build
      install:
          - pip install tox
      script:
          - tox
      after_script:
          - mv tests/coverage.xml .
          - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT tests/coverage.xml

    - stage: delivery
      if: type != pull_request AND branch = master
      env:
        - FOLDER=/package
        - PACKAGE_NAME=prometheus-hanadb_exporter
        - TAR_NAME=hanadb_exporter

      before_install:
        - docker pull shap/continuous_deliver:latest

      script:
        - |
          docker run -t -v "$(pwd):/package" \
          -e OBS_USER -e OBS_PASS -e FOLDER -e OBS_PROJECT -e PACKAGE_NAME -e TAR_NAME shap/continuous_deliver \
          /bin/bash -c "cd /package;/scripts/upload.sh"

    - stage: submit
      if: tag IS present
      env:
        - PACKAGE_NAME=prometheus-hanadb_exporter

      before_install:
        - docker pull shap/continuous_deliver:latest

      script:
        - |
          docker run -t -v "$(pwd):/package" \
          -e OBS_USER -e OBS_PASS -e OBS_PROJECT -e PACKAGE_NAME -e TARGET_PROJECT shap/continuous_deliver \
          /bin/bash -c "cd /package;/scripts/submit.sh"
